### PR TITLE
For issue#6, added user_guide.md

### PR DESCRIPTION
**Pull request by AlperenElbasan**
Added user_guide.md and  changed default.html by one line due to relative_linking.

Any other changes occured because of bundle command, not by me. (speficically: bundle exec jekyll serve)

Please double check for user_guide.md for desired mnemonics list is right. New things can be added to user guide when demanded.

View can be seen here,
https://alperenelbasan.github.io/ETUmulator/user_guide

Alperen.

### CODE REVIEW

**Comment by RootG** [comment]
Instruction mnemonics are incomplete. Please look at [Assembler.g4](https://github.com/kasirgalabs/ETUmulator/blob/1739f15f207d1c1c8ff80680ebd1693eb7982c0b/src/main/antlr/Assembler.g4) file and update your PR.

**Comment by RootG** [comment]
You can ignore the Codacy.

**Comment by AlperenElbasan** [comment]
Ok, on it!

**Comment by AlperenElbasan** [comment]
Updated the user guide. It can be seen here: [Website](https://alperenelbasan.github.io/ETUmulator/user_guide)

**Pull request merged**
